---
title: Annotating NMF factors with sample metadata
author: Zach DeBruine
date: '2021-10-12'
slug: annotating-nmf-factors-with-sample-metadata
categories:
  - NMF
  - annotation
tags:
  - NMF
  - annotation
subtitle: 'Learning bird species communities within the Hawaiian islands'
summary: 'Use the Hawaii Birds dataset to show how to annotate factors in NMF models using metadata, with some interesting UMAP visualizations and applications to ecology along the way.'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "left")
```

## Annotating NMF factors

NMF learns an interpretable low-rank representation of data. However, how do we make sense of the factors in this low-rank latent model? A great way to begin annotating a latent space is to simply map it back to known sample and feature traits.

This vignette demonstrates these concepts using an NMF model of bird species communities throughout the Hawaiian islands.

## Install RcppML

Install the RcppML R package from CRAN or the development version from GitHub. Also install the accompanying Machine Learning datasets (MLdata) package:

```{R, eval = FALSE}
install.packages('RcppML')                     # install CRAN version
# devtools::install_github("zdebruine/RcppML") # compile dev version
devtools::install_github("zdebruine/MLdata")
```

```{R, message = FALSE, warning = FALSE}
library(RcppML)
library(MLdata)
library(ggplot2)
library(cowplot)
library(viridis)
library(ggrepel)
library(uwot)
```

## The hawaiibirds dataset

The `MLdata::hawaiibirds` dataset gives the frequency of bird species in small geographical grids throughout the state of Hawaii. 

```{R}
data(hawaiibirds)
hawaiibirds$counts[1:4, 1:4]
```

A separate `metadata_h` matrix gives the geographical coordinates and the corresponding island for each grid.

```{R}
head(hawaiibirds$metadata_h)
```

And a separate `metadata_w` matrix gives taxonomic information about each species in the database.

```{R}
head(hawaiibirds$metadata_w)
```

## Cross-validation for Rank Determination

We can learn an NMF model to describe linear combinations of species across geographical grids. First we need to choose a rank. 

The rank of a factorization is a crucial hyperparameter. One way to help decide on a rank is cross-validation. This is made easy using the `crossValidate` function. See `?crossValidate` for details on methods.

For many applications, there is no "optimal" rank. In this case, we do expect some amount of distinct biodiversity across the various islands, but within the islands there will be a continuum of habitat niches confounding rank of the signal. Additionally, there may be a number of "missing" observations where surveys were incomplete, which will confound signal separation.

Here we cross-validate across 3 independent replicates and plot the result:

```{R, fig.width = 4, fig.height = 3}
plot(crossValidate(hawaiibirds$counts, k = c(1:10, 12, 15, 20, 25, 30), reps = 3, verbose = FALSE))
```

We'll choose a rank of `k = 10` since this seems to capture much of the signal while giving identifiable factors.

## Run robust NMF

Let's generate a high-quality NMF model across 10 random restarts at very low tolerance:

```{R, results = "hide"}
model <- nmf(hawaiibirds$counts, k = 10, seed = 1:10, tol = 1e-6)
```

```{R}
model
```

In the `w` matrix we have factors describing communities of co-occuring bird species.

In the `h` matrix we have the association of these bird communities in each surveyed geographical grid.

## Geographic focus on NMF factors

What does each NMF factor tell us?

The sample embeddings matrix (`h`) gives information about the geographical representation of each NMF factor across all grids. We'll look at just the first four factors:

```{R, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 4}
plots <- list()
for(i in 1:4){
  df <- data.frame(
    "lat" = hawaiibirds$metadata_h$lat,
    "lng" = hawaiibirds$metadata_h$lng,
    "nmf_factor" = model$h[i, ])
  plots[[i]] <- ggplot(df, aes(x = lng, y = lat, color = nmf_factor)) +
    geom_point() +
    scale_color_viridis(option = "B") +
    theme_void() +
    theme(legend.position = "none", plot.title = element_text(hjust = 0.5)) + 
    ggtitle(paste0("Factor ", i))
}
plot_grid(plotlist = plots, nrow = 2)
```

## Metadata enrichment in factors

Factor 2 is localized largely to the island of Hawaii, factor 3 to the island of Kauai, and factor 4 to Oahu.

Quantitatively, the `summary` method for the `nmf` S3 class makes it easy to annotate factors using metadata about samples or features. See `?summary.nmf` for info.

In this case, we will use `summary` to map factor enrichment in grids corresponding to each Hawaiian island, and species enrichment corresponding to each category.

```{R, fig.width = 4, fig.height = 3}
plot(summary(model, group_by = hawaiibirds$metadata_h$island, stat = "sum"))
```

In general, grids separate based on the island to which they belong -- consistent with the expectation that islands contain distinct species communities. 

Notice how several factors explain variation within the big island, "Hawaii", consistent with the objective of NMF and the biological diversity within that island. 

Due to our normalization method (`sum`) very small islands with minor contribution to the model objective (i.e. Puuwai) are hardly represented.

```{R, fig.width = 4, fig.height = 3}
plot(summary(model, group_by = hawaiibirds$metadata_w$category, stat = "mean"))
```

Clearly, there is the greatest signal complexity among "perching birds". `nmf10` is describing "seabirds" while `nmf9` is capturing much of the "non-perching birds" information.

## NMF biplots

Compare species composition in two factors that are both primarily restricted to the island of Hawaii, factors 7 and 8. The `biplot` S3 method for `nmf` makes this easy:

```{R, message = FALSE, warning = FALSE, fig.width = 5.5, fig.height = 4}
biplot(model, factors = c(7, 8), matrix = "w", group_by = hawaiibirds$metadata_w$category) + 
  scale_y_continuous(trans = "sqrt") + 
  scale_x_continuous(trans = "sqrt") +
  geom_text_repel(size = 2.5, seed = 123, max.overlaps = 15)
```

Factor 7 describes a wet rainforest community while Factor 8 describes dry rainforest/shrubland communities. Both factors are overwhelmingly focused on "perching birds".

## UMAP on NMF embeddings

We might also be interested in visualizing how factors in `w` capture similarities among bird species using UMAP.

```{R, warning = FALSE, message = FALSE, fig.width = 8, fig.height = 2.5}
set.seed(123)
umap <- data.frame(uwot::umap(model$w))
umap$taxon <- hawaiibirds$metadata_w$category
umap$status <- hawaiibirds$metadata_w$status
plot_grid(
  ggplot(umap, aes(x = umap[,1], y = umap[,2], color = taxon)) +
    geom_point() + theme_void(),
  ggplot(umap, aes(x = umap[,1], y = umap[,2], color = status)) +
    geom_point() + theme_void(),
  nrow = 1
)


```

Species are classified based on habitat niche and taxonomic membership. Notice "seabirds" on the left, "perching birds" in the center mixed with "non-perching birds", and a mix of "waders", "waterfowl", and "shorebirds" in the bottom right. There are also two distinct groups of "shorebirds" and "waterfowl", consistent with distinct inland and shoreline communities.

Hawaii is extinction kingdom. For instance, more than 20 species of endemic honeycreeper have gone extinct in the past two centuries due to the establishment of introduced species and habitat devastation. Few remain. In the UMAP plot above on the right, we can observe that introduced species dominate habitat niches occupied by native perching and non-perching birds, a problem underlying historic and ongoing mass extinction events.

```{R, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 2.5}
set.seed(123)
umap <- data.frame(uwot::umap(t(model$h)))
umap$group <- hawaiibirds$metadata_h$island
ggplot(umap, aes(x = umap[,1], y = umap[,2], color = group)) +
  geom_point() + theme_void()
```

Islands are also well-defined by the NMF model.

## Defining the "Palila" species niche

The [Palila](https://ebird.org/media/catalog?taxonCode=palila&mediaType=p&sort=rating_rank_desc&q=Palila%20-%20Loxioides%20bailleui) is a highly endangered species that survives in small numbers on the eastern slopes of Mauna Kea on the dry island, in a shrubby dry "rainforest" biome. This biome is unique on the island of Hawaii.

What species coexist with the Palila?

Let's find the highest factorization resolution at which a single factor describes the distribution of the Palila.

```{R, fig.height = 3, fig.width = 4}
palila <- list()
for(rank in 1:20)
  palila[[rank]] <- data.frame(
    "value" = nmf(hawaiibirds$counts, k = rank, seed = 123, v = F)$w["Palila", ],
    "rank" = rep(rank, rank)
  )
palila <- do.call(rbind, palila)
ggplot(palila, aes(x = rank, y = value, color = factor(rank))) + geom_jitter(width = 0.1) + theme_classic() +
  scale_color_manual(values = rep(c("#F8766D", "#00BDD0"), 10)) + labs("Palila loading in factor") + theme(legend.position = "none")
```

The model with a rank of 15 contains a factor in which the Palila is both important and specific.

Let's have a look at the species composition in factor 15, specifically identifying which species are introduced and which are native:

```{R}
model <- nmf(hawaiibirds$counts, k = 15, seed = 123, v = F)
df <- data.frame("value" = model$w[, which.max(model$w["Palila", ])])
df$status <- hawaiibirds$metadata_w$status
df <- df[order(-df$value), ]
df <- df[df$value > 0.001, ]
df
```

The diet of the Palilla is largely seeds from the "mamame" tree, but also naio berries and mamame flowers, buds, and young leaves. What introduced perching birds may be competing with the Palila for these resources?

```{R}
perching_birds <- hawaiibirds$metadata_w$species[hawaiibirds$metadata_w$category == "perching birds"]
df[which(rownames(df) %in% perching_birds & df$status == "introduced"), ]
```

The "House Finch" and "Yellow-fronted Canary" seem to be the most significant competitors in the Palila habitat niche.