---
title: "Statistical properties of L1- and L2-regularized NMF"
author: "Zach DeBruine"
date: '2021-10-18'
slug: l2-regularized-nmf
categories:
- NMF
- methods
tags:
- NMF
- regularization
- L2
subtitle: An intuitive take on what exactly L1- and L2-regularized NMF actually does
summary: L1- and L2-regularized non-negative matrix factorizations have special properties. Here I show how L1 is a sparsifying regularization that promotes
  a k-means clustering-like model, while L2 is a densifying regularization that promotes
  convergence of all factors towards the first singular vector.
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "left")
```

## Key Takeaways

For non-negative matrix factorization:

* L1 and L2 regularization require diagonalization (factorization of the form $A = wdh$)
* L1 is a sparsifying, L2 is densifying
* L1 increases angle between factors, L2 decreases angle between factors
* L1 penalties cause factors to converge collectively towards a k-means clustering model, L2 penalties cause each factor to converge individually towards the first singular vector

## Regularizing NMF

Regularizations are intended to improve the interpretability or identifiability of linear models. Consider the least squares problem $ax = b$, for which common regularizations include:

* **L1/LASSO** regularization: absolute shrinkage, penalty subtracted from $b$
* **L2/Ridge** regularization: convex shrinkage, penalty added to diagonal of $a$

In a typical non-negative least squares (NNLS) fit, these regularizations behave usefully. For example, an L1 penalty equal to the maximum value in $b$ will ensure complete sparsity of the solution.

Now consider NMF by alternating least squares.  NMF differs from one-off least squares problems in several ways:

* It is iterative
* The initial distribution of the models are unknown (i.e. projection of random factors)
* The distribution of a model at a given iteration is dependent on that of the models at all previous iterations

Thus, NMF regularizations have a chain effect:  a change in one iteration will lead to a change in information and distribution in the next, and so forth. Thus, if the distribution of the model is not controlled after each update, penalties will cause the model to spiral out of control.

## Controlling NMF model distributions during updates

NMF minimizes $A = wh$. The least squares update of $h$, column $j$ given $A$ and $w$ is:

$$w^Twh_j = w^TA_j$$

Correspondingly, the least squares update of $w$, row $j$, given $A$ and $h$ is:

$$hh^Tw_j = hA^T_j$$
These equations are in the form $ax = b$. For instance, in the update of $h$, $a = w^Tw$ and $b = w^TA_j$. 

For a regularization penalty strictly in the range (0, 1], we want to guarantee that the penalty will be consistent across random NMF restarts, different datasets, and across alternating least squares updates. To guarantee consistent application of the penalty, we need to control the distribution of $a$ and $b$. 

The distribution of a model can be controlled by diagonalizing the NMF model, such that $A = wdh$, where columns in $w$ and rows in $h$ are scaled to sum to 1 by a scaling diagonal, $d$. Factors need not scale to 1, it could be any constant value, but 1 provides nice interpretability.

## Diagonalized NMF enables convex regularization

Let's load the `hawaiibirds` dataset and factorize the data at several L1 and L2 penalties, with and without model diagonalization, also calculating various statistics such as sparsity, similarity to k-means clustering, and similarity to the first singular vector.

```{R install_stuff, warning = FALSE, message = FALSE}
# devtools::install_github("zdebruine/RcppML")
library(RcppML)
data(hawaiibirds)
A <- hawaiibirds$counts
```

```{R}
alphas <- c(c(1, 3, 5, 9) %o% 10^(-3:-1)) # c(seq(0, 0.1, 0.005), seq(0.11, 0.5, 0.01)) # seq(0, 0.98, 0.02)
seeds <- c(123, 456, 789)
kmeans_centers <- t(kmeans(t(as.matrix(A)), 10)$centers)
svd1 <- nmf(A, 1)@w
df <- data.frame()
for(alpha in alphas){
  for(seed in seeds){
    for(diag in c(FALSE, TRUE)){
      m <- nmf(A, 10, seed = seed, diag = diag)
        for(penalty in c("L1", "L2")){
        m_ <- nmf(A, 10, seed = seed, diag = diag,
                   L1 = ifelse(penalty == "L1", alpha, 0), 
                   L2 = ifelse(penalty == "L2", alpha, 0),
                  )
        df <- rbind(df, data.frame(
          "alpha" = alpha,
          "seed" = seed,
          "diag" = diag,
          "penalty" = penalty,
          "sparsity" = sum(m_@w == 0) / prod(dim(m_@w)),
          "robustness" = 1 - bipartiteMatch(1 - cosine(m_@w, m@w))$cost/10,
          "mse" = evaluate(m_, A),
          "mean_angle" = mean(cosine(m_@w)),
          "kmeans" = bipartiteMatch(1 - cosine(kmeans_centers, m_@w))$cost/10,
          "svd1" = sum(cosine(m_@w, svd1))/10,
          "color" = ifelse(penalty == "L1", alpha^0.25, -alpha^0.25)
        ))      
      }
    }
  }
}
df$penalty <- factor(df$penalty)
df$seed <- factor(df$seed)
```

```{R, echo = FALSE, fig.height = 6, fig.width = 8, warning = FALSE, message = FALSE}
library(ggplot2)
library(cowplot)
p1 <- ggplot(subset(df, diag == FALSE & penalty == "L1"), aes(x = alpha, y = sparsity, color = seed)) +
  geom_point() + labs(x = "L1 penalty", y = "sparsity of 'w'") + ggtitle("no scaling") +
  theme_classic() + theme(plot.title = element_text(hjust = 0.5), aspect.ratio = 1) + scale_y_continuous(limits = c(0.6, 1)) + scale_x_continuous(trans = "log10") +
  stat_smooth(se = F)
p2 <- ggplot(subset(df, diag == TRUE & penalty == "L1"), aes(x = alpha, y = sparsity, color = seed)) +
  geom_point() + labs(x = "L1 penalty", y = "sparsity of 'w'") + ggtitle("with scaling") +
  theme_classic() + theme(plot.title = element_text(hjust = 0.5), aspect.ratio = 1) + scale_y_continuous(limits = c(0.6, 1))  + scale_x_continuous(trans = "log10") +
  stat_smooth(se = F)
p3 <- ggplot(subset(df, diag == FALSE & penalty == "L2"), aes(x = alpha, y = sparsity, color = seed)) +
  geom_point() + labs(x = "L2 penalty", y = "sparsity of 'w'") + ggtitle("no scaling") +
  theme_classic() + theme(plot.title = element_text(hjust = 0.5), aspect.ratio = 1)  + scale_x_continuous(trans = "log10") +
  stat_smooth(se = F)
p4 <- ggplot(subset(df, diag == TRUE & penalty == "L2"), aes(x = alpha, y = sparsity, color = seed)) +
  geom_point() + labs(x = "L2 penalty", y = "sparsity of 'w'") + ggtitle("with scaling") +
  theme_classic() + theme(plot.title = element_text(hjust = 0.5), aspect.ratio = 1) + scale_x_continuous(trans = "log10") +
  stat_smooth(se = F)
plot_grid(
  plot_grid(p1 + theme(legend.position = "none"),
          p2 + theme(legend.position = "none"),
          p3 + theme(legend.position = "none"),
          p4 + theme(legend.position = "none"),
          nrow = 2, ncol = 2, labels = "auto"),
  get_legend(p1),
  rel_widths = c(1, 0.2), nrow = 1)
```

Takeaways:

* Diagonal scaling guarantees consistent regularization between independent replicates (compare **a**, **c** with **b**, **d**)
* L1 regularization increases sparsity of factor models (**b**) while L2 regularization promotes density of the model (**d**)
* L1 = 1 guarantees complete sparsity (**b**) while L2 = 1 guarantees complete density (**d**)

We might not have expected that L2 is a densifying factorization. Why is this?  L2 convexly shrinks values towards zero, and as such decreases the condition number of $a$. This means signals will be encouraged to "squash" together, and factors in the resulting model will begin to describe similar signal. As this occurs, the model naturally becomes denser until a point is reached that the objective is minimized (at convergence).

## Properties of L1- and L2-regularized NMF

Let's consider how L1 and L2 regularizations affect the robustness of information content of factor models relative to the unregularized equivalent, and how they affect the mean squared error loss of the models.

As a measure of the robustness of information content, we use the mean cost of bipartite matching between L1-regularized and unregularized $w$ models on a cosine similarity matrix. 

```{R, fig.width = 7, fig.height = 3, echo = FALSE, warning = FALSE, message = FALSE}
p1 <- ggplot(subset(df, diag == TRUE & seed == 123), aes(x = alpha, y = robustness, color = penalty)) +
  geom_point() + labs(y = "similarity to\nunregularized model") +
  theme_classic() + theme(aspect.ratio = 1) + scale_x_continuous(trans = "log10") +
  stat_smooth(se = F)
p2 <- ggplot(subset(df, diag == TRUE & seed == 123), aes(x = alpha, y = mse, color = penalty)) +
  geom_point() + labs(y = "MSE") +
  theme_classic() + theme(aspect.ratio = 1) + scale_x_continuous(trans = "log10") +
  stat_smooth(se = F)

plot_grid(p1 + theme(legend.position = "none"),
          p2 + theme(legend.position = "none"),
          get_legend(p1),
          nrow = 1, labels = c("a", "b", ""), rel_widths = c(1, 1, 0.4))
```

Notice how the L2 penalties tend to be much harsher than the L1 penalties. However, both penalties cause movement of the model away from the unregularized state.

Within the models themselves, we can examine how similar factors are to one another by measuring the mean cosine angle:

```{R, fig.width = 4, fig.height = 3, warning = FALSE, message = FALSE}
ggplot(subset(df, diag == TRUE & seed == 123), aes(x = alpha, y = mean_angle, color = penalty)) +
  geom_point() + labs(x = "alpha", y = "mean cosine angle\nbetween factors") +
  theme_classic() + theme(aspect.ratio = 1) + scale_x_continuous(trans = "sqrt") +
  stat_smooth(se = F)
```

We can see that L1 penalty increases the distance between factors, while L2 penalty increases the similarity between factors.

Now let's take a look at how L1 and L2 penalties affect the sparsity of factors, and also calculate the similarity of these models to a k-means clustering or the first singular vector (given by a rank-1 NMF):

```{R, fig.width = 7, fig.height = 3, echo = FALSE, warning = FALSE, message = FALSE}
ggplot(subset(df, diag == TRUE & seed == 123), aes(x = sparsity, y = alpha, color = color)) + geom_point(size = 2) + theme_classic() +
  theme(aspect.ratio = 1) + 
  scale_y_continuous(trans = 'log10') +
  scale_color_gradient2(low = "#ff0000",
                        mid = "#cccccc",
                        high = "#0000ff",
                        breaks=c(-1,0,1),
                        labels=c("L1 = 1",0,"L2 = 1"),
                        limits=c(-1,1)) +
  labs(y = "alpha", x = "sparsity of 'w'")
```

L1 is sparsifying while L2 is densifying.

```{R, fig.width = 7, fig.height = 3, echo = FALSE, warning = FALSE, message = FALSE}
p2 <- ggplot(subset(df, penalty != "none" & diag == TRUE & seed == 123), aes(x = alpha, y = kmeans, color = factor(penalty))) + geom_point(size = 2) + theme_classic() +
  theme(aspect.ratio = 1) + geom_smooth(se = F) +
  scale_x_continuous(trans = 'log10') +
  labs(y = "similarity of factor model\nto k-means clustering", x = "alpha") +
  guides(color = guide_legend(title = "penalty"))

p3 <- ggplot(subset(df, penalty != "none" & diag == TRUE & seed == 123), aes(x = alpha, y = svd1, color = factor(penalty))) + geom_point(size = 2) + theme_classic() +
  theme(aspect.ratio = 1) + geom_smooth(se = F) +
  scale_x_continuous(trans = 'log10') +
  labs(y = "mean similarity of all factors\nto first singular vector", x = "alpha") +
  guides(color = guide_legend(title = "penalty"))

plot_grid(p2 + theme(legend.position = "none"), p3 + theme(legend.position = "none"), get_legend(p2), nrow = 1, rel_widths = c(1, 1, 0.4))
```

Here, L1 promotes a k-means clustering model while L2 promotes convergence towards the first singular vector.

## Interpreting L1- and L2-regularized factor models

We'll select regularization parameters for further analysis based on a cosine angle of about 0.25 away from the original model:

```{R}
model    <- nmf(A, 10, tol = 1e-6, seed = 123)
model_L1 <- nmf(A, 10, tol = 1e-6, seed = 123, L1 = 0.2)
model_L2 <- nmf(A, 10, tol = 1e-6, seed = 123, L2 = 0.02)
```

Take a look at the clustering of factors in the $w$ models on UMAP coordinates:

```{R, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 3, fig.height = 3}
library(uwot)
colnames(model@w) <- rep("default", 10)
colnames(model_L1@w) <- rep("L1", 10)
colnames(model_L2@w) <- rep("L2", 10)
m <- t(cbind(model$w, model_L1$w, model_L2$w))
set.seed(123)
umap_coords <- uwot::umap(m, n_neighbors = 3, metric = "cosine")
umap_coords <- data.frame("umap1" = umap_coords[,1], "umap2" = umap_coords[,2], "model" = rownames(m))
ggplot(umap_coords, aes(x = umap1, y = umap2, color = model)) + geom_point() + theme_void()
```

Similar information is clearly being captured by each of the models, but let's see in what way. 

We'll align factors in the regularized models to the unregularized models, and then compare specific factors.

```{R, warning = FALSE}
library(ggrepel)
biplot <- function(model1, model2, factor){
  df <- data.frame("model1" = model1$w[, factor], "model2" = model2$w[, factor], "label" = rownames(model1$w))
  ggplot(df, aes(x = model1, y = model2, label = label)) + geom_point() + theme_classic() + geom_text_repel(size = 2.5)
}

model_L1 <- align(model_L1, model)
model_L2 <- align(model_L2, model)
```

```{R, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 6, echo = FALSE}
p1 <- biplot(model, model_L1, 1) + labs(x = "No penalty", y = "L1 = 0.2") + 
  theme(aspect.ratio = 1, plot.title = element_text(hjust = 0.5)) + ggtitle("factor 1")
p2 <- biplot(model, model_L1, 8) + labs(x = "No penalty", y = "L1 = 0.2") + 
  theme(aspect.ratio = 1, plot.title = element_text(hjust = 0.5)) + ggtitle("factor 8")
p3 <- biplot(model, model_L2, 1) + labs(x = "No penalty", y = "L2 = 0.02") + 
  theme(aspect.ratio = 1, plot.title = element_text(hjust = 0.5)) + ggtitle("factor 1")
p4 <- biplot(model, model_L2, 8) + labs(x = "No penalty", y = "L2 = 0.02") + 
  theme(aspect.ratio = 1, plot.title = element_text(hjust = 0.5)) + ggtitle("factor 8")
plot_grid(p1, p2, p3, p4, nrow = 2, ncol = 2, labels = "auto")
```

These are very harsh penalties, so notice how L1 can over-sparsify things, while L2 can generate factors that are so dense the information is hardly specific or informative.

A happy medium for sparsifying (or densifying) regularization certainly exists, and this is an objective hyperparameter that must be determined against the objectives of the analysis. Unfortunately, there is nothing against which to optimize -- this appears to be a matter of statistical taste.

## Future directions

* Effect of L1 and L2 regularizations on factorization rank
* Intuition behind one-sided L1 and L2 regularization
* Intuition behind combined L1/L2 or one-sided L1 vs. one-sided L2